config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, only: %i[show edit update]
  resources :categories, only: %i[index]
  resources :relationships, only: [:create, :destroy]

  resources :lessons, only: %i[create show update] do
    member do
      get :result
    end
  end

  namespace :admin do
   root 'admin_pages#index'
   resources :categories
   resources :words
  end
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  belongs_to :category
  has_many :lesson_words, dependent: :destroy
  has_many :lessons, through: :lesson_words
  has_many :word_answers, dependent: :destroy

  accepts_nested_attributes_for :word_answers

  validates :content, presence: true, length: { maximum: 20 }
  validates :category_id, presence: true

  def correct_answer
    word_answers.where(correct: true).first
  end
end

app/controllers/admin/words_controller.rb
# frozen_string_literal: true

class Admin::WordsController < ApplicationController
  before_action :find_word, only: %i[show edit update destroy]

  def index
    @words = Word.order(created_at: :desc)
  end

  def new
    @categories = Category.order(:name)
    @word = Word.new
    3.times { @word.word_answers.new }
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = 'Create word successfully'
      redirect_to admin_word_path(@word)
    else
      flash.now[:alert] = 'Create word failed'
      render :new
    end
  end

  def destroy
    @word.destroy
    flash[:success] = "Delete word successfully"
    redirect_to admin_words_path(@word)
  end

  def edit; end

  def update
    if @word.update_attributes(word_params)
      flash[:notice] = 'Updated word successfully'
      redirect_to admin_word_path(@word)
    else
      flash.now[:alert] = 'Updated word failed'
      render :edit
    end
  end

  def show
    @word_answers = @word.word_answers
  end

  private
    def word_params
      params.require(:word).permit :content, :category_id, word_answers_attributes: [:id, :content, :word_id, :correct]
    end

    def find_word
      @word = Word.find(params[:id])
    end
end

app/views/admin/words/_word_answer_fields.html.erb
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <div class="input-group-text">
      <%= f.check_box :correct, type: 'checkbox' %>
    </div>
  </div>
  <%= f.text_field :content, class: 'form-control col-md-6', placeholder: "Enter word answer's content" %>
</div>

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit word') %>
<% provide(:button_text, 'Save') %>
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <h1 class="text-center">Admin | Update Words </h1>
      <%= form_for([:admin, @word]) do |f| %>
        <%= render 'shared/errors_messages', object: f.object %>

        <div class="form-group col-md-9 ">
          <%= f.label :content %>
          <%= f.text_field :content, class:'form-control',placeholder:"Enter word's content" %><br>
          <%= f.text_field :content, class:'form-control', placeholder: "Enter word's content" %><br>
        </div>

        <%= f.fields_for :word_answers do |builder| %>
          <div class="">
            <%= render "word_answer_fields", :f => builder %>
          </div>
        <% end %>

        <div class="text-center">
          <%= f.submit "Update Word", class: 'btn btn-primary' %>
        </div>

        <div class="col-lg-13">
          <%= link_to "Back", admin_words_path, class: 'btn btn-info pull-right' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-lg-12">
          <h3 class="text-center"> Admin | List Words </h3>
        </div>
      </div>
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Content</th>
          <th>Creation time</th>
          <th>Update time</th>
          <th>Answer Correct</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @words.each do |word| %>
          <tr>
            <td><%= link_to(word.content, admin_word_path(word)) %></td>
            <td><%= word.created_at %></td>
            <td><%= word.updated_at %></td>
            <td><%= word.correct_answer&.content %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><br>
  <div class="col-lg-13">
    <%= link_to "Add New Word", new_admin_word_path, class: 'btn btn-info pull-right' %>
    <%= link_to "Back", admin_root_path, class: 'btn btn-info pull-right' %>
  </div>
</div>

app/views/admin/words/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <h1 class="text-center">Create Word </h1>
      <%= form_for @word, url: admin_words_path do |f| %>
        <%= render 'shared/errors_messages', object: @word %>

        <div class="form-group col-md-7">
          <%= f.label :content %>
          <%= f.text_field :content, class: 'form-control', placeholder: "Enter your content Word" %><br>
        </div>

        <div class="form-group">
          <%= f.label :category %>
          <%= f.collection_select :category_id, @categories, :id, :name, include_blank: true %>
        </div>

        <%= f.fields_for :word_answers do |builder| %>
          <div class="">
            <%= render "word_answer_fields", :f => builder %>
          </div>
        <% end %>
        <div class="text-center">
          <%= f.submit "Create", class: 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to 'Home Admin', admin_root_path, class: 'btn btn-info pull-right' %>
      <%= link_to "Back", admin_words_path, class: 'btn btn-info pull-right' %>
    </div>
  </div>
</div>

app/views/admin/words/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-lg-9">
          <h3 class="text-center">Admin | Word: <%= @word.content %></h3>
        </div>

        <div class="col-lg-3">
          <%= link_to "Edit", edit_admin_word_path, class: 'btn btn-primary' %>
          <%= link_to "Delete",admin_word_path,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
        </div>
      </div>
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Content</th>
          <th>Creation time</th>
          <th>Update time</th>
          <th>Answer Correct</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @word_answers.each do |word_answers| %>
          <tr>
            <td><%= word_answers.content %></td>
            <td><%= word_answers.created_at %></td>
            <td><%= word_answers.updated_at %></td>
            <td><%= word_answers.correct %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><br>
  <div class="col-lg-13">
    <%= link_to "Categories List", admin_categories_path, class: 'btn btn-info pull-right' %>
    <%= link_to "Back", admin_words_path, class: 'btn btn-info pull-right' %>
  </div>
</div>