config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, only: %i[show edit update]
  resources :categories, only: %i[index]
  resources :relationships, only: [:create, :destroy]

  resources :lessons, only: %i[create show update] do
    member do
      get :result
    end
  end

  namespace :admin do
   root 'admin_pages#index'
   resources :categories
   resources :words
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  mount_uploader :avatar, AvatarUploader
  has_many :lessons, dependent: :destroy
  has_many :following_relationships,  class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy

  def follow(user)
    following_relationships.create(following_id: user.id)
  end

  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  has_many :following, through: :following_relationships, source: :following
  has_many :followers, through: :follower_relationships, source: :follower

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :fullname, presence: true
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'Sign Up Success'
      redirect_to root_path
    else
      flash.now[:warning] = 'Registration Failed'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Update Success'
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find_by id: params[:id]
  end

private
  def user_params
    params.require(:user).permit :email, :fullname, :password, :password_confirmation, :avatar
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :fullname %>
  <%= f.text_field :fullname, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar, class: 'form-control' %><br>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save') %>
<h1>Update</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">Sign up</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for :user, url: users_sign_up_path do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :fullname %>
          <%= f.text_field :fullname, placeholder: "Enter your fullname", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, placeholder: "Enter your password_confirmation", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class:'form-control', placeholder: "Enter image" %>
        </div>

        <div class="text-center">
          <%= f.submit "Sign up", class: "btn btn-info col-lg-12" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label>
          <strong>Email:</strong>
          <%= @user.email %>
        </label><br>
        <label>
          <strong>fullname:</strong>
          <%= @user.fullname %>
        </label><br>
        <label>
          <strong>Avatar:</strong>
          <%= image_tag(@user.avatar_url) if @user.avatar? %>
        </label>
      </div>
      <div class="col-lg-offset-3 col-lg-6">
        <% if signed_in? %>
          <% if @user == current_user %>
            <div class="row">
              <div class="col-lg-6">
                <strong id="following"><%= link_to @user.following.count %></strong>
                <div>following</div>
              </div>
              <div class="col-lg-6">
                <strong id="followers"><%= link_to @user.followers.count %></strong>
                <div>followers</div>
              </div>
            </div>
          <% else %>
            <% if current_user.following?(@user) %>
              <%= button_to 'Following', relationship_path(user_id: @user.id), class: 'btn unfollow-button', method: :delete %>
            <% else %>
              <%= button_to 'Follow', relationships_path(user_id: @user.id), class: 'btn follow-button' %>
            <% end %>
          <% end %>
        <% else %>
          <div class="row">
            <div class="col-lg-6">
              <strong id="following"><%= link_to @user.following.count %></strong>
              <div>following</div>
            </div>
            <div class="col-lg-6">
              <strong id="followers"><%= link_to @user.followers.count %></strong>
              <div>followers</div>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to "Edit", edit_user_path(@user), class:"btn btn-primary" %>
      <%= link_to "Log_out", log_out_path, method: :delete %>
    </div>
  </div>
</div>