config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, only: %i[show edit update]
  resources :categories, only: %i[index]
  resources :relationships, only: [:create, :destroy]

  resources :lessons, only: %i[create show update] do
    member do
      get :result
    end
  end

  namespace :admin do
   root 'admin_pages#index'
   resources :categories
   resources :words
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.order(created_at: :desc)
  end

  def new; end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = 'Create category successfully'
      redirect_to admin_categories_path
    else
      flash[:alert] = 'Create category failed'
      render :new
    end
  end

  def show
    @words = @category.words
  end

  def destroy
    @category.destroy
    flash[:success] = "Delete category successfully"
    redirect_to admin_categories_url
  end

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Updated category successfully'
      redirect_to admin_categories_url
    else
      flash.now[:alert] = 'Updated category failed'
      render :edit
    end
  end

private
  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/views/admin/categories/edit.html.erb
<% provide(:title, 'Edit category') %>
<% provide(:button_text, 'Save') %>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Admin | Update Category</h1>
      <%= form_for([:admin, @category]) do |f| %>
        <%= render 'shared/errors_messages', object: f.object %>

        <div class="form-group row">
          <label for="staticName" class="col-sm-2 col-form-label">Category Name</label>

          <div class="col-sm-10">
            <%= f.text_field :name, class:'form-control', placeholder: "Enter category's name" %>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Update Category", class: 'btn btn-primary' %>
        </div>

        <div class="col-lg-13">
          <%= link_to "Back", admin_categories_path, class: 'btn btn-info pull-right' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-lg-12">
          <h3 class="text-center">
            Admin | List Categories
          </h3>
        </div>
      </div>
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Category</th>
          <th>Number of words</th>
          <th>Creation time</th>
          <th>Update time</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to(category.name, admin_category_path(category)) %></td>
            <td><%= category.words.count %></td>
            <td><%= category.created_at %></td>
            <td><%= category.updated_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><br>
  <div class="col-lg-13">
    <%=link_to 'Create New Category',new_admin_category_path, class: "btn btn-info pull-right" %>
    <%= link_to 'Back', admin_root_path, class: 'btn btn-info pull-right' %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <h1 class="text-center">Create Categories</h1>
      <%= form_for Category.new ,url: admin_categories_path do |f| %>

        <div class="form-group">
          <%= f.label:name %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'enter category name' %>
        </div>

        <div class="text-center">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div><br>
      <% end %>
      <%= link_to 'Home Admin', admin_root_path, class: 'btn btn-info pull-right' %>
      <%= link_to "Back", admin_categories_path, class: 'btn btn-info pull-right' %>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-lg-9">
          <h3 class="text-center">Admin | Category: <%= @category.name %></h3>
        </div>

        <div class="col-lg-3">
          <%= link_to "Edit", edit_admin_category_path, class: 'btn btn-primary' %>
          <%= link_to "Delete",admin_category_path,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
        </div>
      </div>
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Content</th>
          <th>Creation time</th>
          <th>Update time</th>
          <th>Answer Correct</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @words.each do |word| %>
          <tr>
            <td><%= link_to(word.content, admin_word_path(word)) %></td>
            <td><%= word.created_at %></td>
            <td><%= word.updated_at %></td>
            <td><%= word.correct_answer&.content %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-lg-13"><br>
    <%= link_to "Words List", admin_words_path, class: 'btn btn-info pull-right' %>
    <%= link_to "Back", admin_categories_path, class: 'btn btn-info pull-right' %>
  </div>
</div>