config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, only: %i[show edit update]
  resources :categories, only: %i[index]
  resources :relationships, only: [:create, :destroy]

  resources :lessons, only: %i[create show update] do
    member do
      get :result
    end
  end

  namespace :admin do
   root 'admin_pages#index'
   resources :categories
   resources :words
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="color:'black'">
          <li class="nav-item active nav-link">
            <%= link_to 'Home', root_path %>
          </li>
        <% if signed_in? %>
          <li class="nav-item nav-link">
            <%= link_to 'Category', categories_path %>
          </li>
        <% else %>
          <li class="nav-item nav-link">
            <%= link_to 'Sign up', users_sign_up_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to 'Sign In', users_sign_in_path %>
          </li>
        <% end %>
        </ul>
      </div>
    <% if signed_in? %>
      <div class="nav-item nav-link">
        <%= link_to "My profile", user_path(current_user) %>
      </div>
    <% end %>
    </nav>
    <%= render 'shared/flashregister'%>
    <%= yield %>
  </body>
</html>